package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val SleekPrimary = Color(0xFF386A20)
val SleekPrimaryContainer = Color(0xFFD7E8CD)
val SleekBackground = Color(0xFFFBFDF8)
val SleekSurface = Color(0xFFFFFFFF)
val SleekSurfaceVariant = Color(0xFFE7F3DE)
val SleekOnBackground = Color(0xFF191C19)
val SleekOutline = Color(0xFFE1E4DC)
val SleekOutlineVariant = Color(0xFFF1F3EE)

val SleekPrimaryDark = Color(0xFF9CD67D)
val SleekPrimaryContainerDark = Color(0xFF205107)
val SleekBackgroundDark = Color(0xFF11140F)
val SleekSurfaceDark = Color(0xFF11140F)
val SleekSurfaceVariantDark = Color(0xFF42493E)
val SleekOnBackgroundDark = Color(0xFFE1E4DC)
val SleekOutlineDark = Color(0xFF8B9386)
val SleekOutlineVariantDark = Color(0xFF42493E)

// Ocean Theme
val OceanPrimary = Color(0xFF006493)
val OceanPrimaryContainer = Color(0xFFCAE6FF)
val OceanBackground = Color(0xFFFCFCFF)
val OceanSurface = Color(0xFFFFFFFF)
val OceanSurfaceVariant = Color(0xFFDDE3EA)
val OceanOnBackground = Color(0xFF1A1C1E)

val OceanPrimaryDark = Color(0xFF8DCDFF)
val OceanPrimaryContainerDark = Color(0xFF004B70)
val OceanBackgroundDark = Color(0xFF1A1C1E)
val OceanSurfaceDark = Color(0xFF1A1C1E)
val OceanSurfaceVariantDark = Color(0xFF41474D)
val OceanOnBackgroundDark = Color(0xFFE2E2E5)

// Sunset Theme
val SunsetPrimary = Color(0xFFA04100)
val SunsetPrimaryContainer = Color(0xFFFFDBCB)
val SunsetBackground = Color(0xFFFFFBFF)
val SunsetSurface = Color(0xFFFFFFFF)
val SunsetSurfaceVariant = Color(0xFFF4DED4)
val SunsetOnBackground = Color(0xFF201A18)

val SunsetPrimaryDark = Color(0xFFFFB68F)
val SunsetPrimaryContainerDark = Color(0xFF7A3000)
val SunsetBackgroundDark = Color(0xFF201A18)
val SunsetSurfaceDark = Color(0xFF201A18)
val SunsetSurfaceVariantDark = Color(0xFF52443D)
val SunsetOnBackgroundDark = Color(0xFFEDE0DB)

// Lavender Theme
val LavenderPrimary = Color(0xFF7D5260)
val LavenderPrimaryContainer = Color(0xFFFFD8E4)
val LavenderBackground = Color(0xFFFFFBFF)
val LavenderSurface = Color(0xFFFFFFFF)
val LavenderSurfaceVariant = Color(0xFFF2DDE1)
val LavenderOnBackground = Color(0xFF1E1B1E)

val LavenderPrimaryDark = Color(0xFFEFB8C8)
val LavenderPrimaryContainerDark = Color(0xFF633B48)
val LavenderBackgroundDark = Color(0xFF1E1B1E)
val LavenderSurfaceDark = Color(0xFF1E1B1E)
val LavenderSurfaceVariantDark = Color(0xFF4E444B)
val LavenderOnBackgroundDark = Color(0xFFE8E0E5)
// Cyberpunk Theme
val CyberpunkPrimary = Color(0xFF00FF9D)
val CyberpunkPrimaryContainer = Color(0xFF003320)
val CyberpunkBackground = Color(0xFF09090B)
val CyberpunkSurface = Color(0xFF18181B)
val CyberpunkSurfaceVariant = Color(0xFF27272A)
val CyberpunkOnBackground = Color(0xFFFAFAFA)
val CyberpunkOutline = Color(0xFF3F3F46)
val CyberpunkOutlineVariant = Color(0xFF52525B)

val CyberpunkPrimaryDark = Color(0xFF00FF9D)
val CyberpunkPrimaryContainerDark = Color(0xFF003320)
val CyberpunkBackgroundDark = Color(0xFF09090B)
val CyberpunkSurfaceDark = Color(0xFF18181B)
val CyberpunkSurfaceVariantDark = Color(0xFF27272A)
val CyberpunkOnBackgroundDark = Color(0xFFFAFAFA)
val CyberpunkOutlineDark = Color(0xFF3F3F46)
val CyberpunkOutlineVariantDark = Color(0xFF52525B)

// Emerald Forest Theme
val EmeraldPrimary = Color(0xFF2E7D32)
val EmeraldPrimaryContainer = Color(0xFFA5D6A7)
val EmeraldBackground = Color(0xFFF1F8E9)
val EmeraldSurface = Color(0xFFFFFFFF)
val EmeraldSurfaceVariant = Color(0xFFC8E6C9)
val EmeraldOnBackground = Color(0xFF1B5E20)
val EmeraldOutline = Color(0xFF81C784)
val EmeraldOutlineVariant = Color(0xFFE8F5E9)

val EmeraldPrimaryDark = Color(0xFF81C784)
val EmeraldPrimaryContainerDark = Color(0xFF1B5E20)
val EmeraldBackgroundDark = Color(0xFF0D1D10)
val EmeraldSurfaceDark = Color(0xFF132B18)
val EmeraldSurfaceVariantDark = Color(0xFF2E4032)
val EmeraldOnBackgroundDark = Color(0xFFE8F5E9)
val EmeraldOutlineDark = Color(0xFF4CAF50)
val EmeraldOutlineVariantDark = Color(0xFF388E3C)
val MidnightPrimary = Color(0xFF818CF8)
val MidnightPrimaryContainer = Color(0xFF312E81)
val MidnightBackground = Color(0xFF0F172A)
val MidnightSurface = Color(0xFF1E293B)
val MidnightSurfaceVariant = Color(0xFF334155)
val MidnightOnBackground = Color(0xFFF8FAFC)
val MidnightOutline = Color(0xFF475569)
val MidnightOutlineVariant = Color(0xFF64748B)

val MidnightPrimaryDark = Color(0xFF818CF8)
val MidnightPrimaryContainerDark = Color(0xFF312E81)
val MidnightBackgroundDark = Color(0xFF0F172A)
val MidnightSurfaceDark = Color(0xFF1E293B)
val MidnightSurfaceVariantDark = Color(0xFF334155)
val MidnightOnBackgroundDark = Color(0xFFF8FAFC)
val MidnightOutlineDark = Color(0xFF475569)
val MidnightOutlineVariantDark = Color(0xFF64748B)
